import {
  CATALOG_SOURCE_LABELS,
  FDB_ATTRIBUTION,
  PRIORITY_TOP_SCORE,
} from "@/config/catalog";
import { SECTION_FOR, sectionText } from "@/lib/catalog/to-program";
import type { CatalogChange, CatalogProgram } from "@/types/catalog";
import { COLORS, escapeHtml, primaryLink, type DigestContent } from "./digest-email";

/**
 * Renders the priority alert — NEW programs only, strongest match first.
 *
 * Same constraints as the weekly digest (table layout, inline styles), plus
 * one more: this mail is read on a phone within minutes of arriving. So there
 * are no side-by-side columns, every fact is one wrapping line, and the most
 * important entry is the first thing on screen.
 *
 * Nothing here is generated by a model: score, topics and reasons come from
 * `topic-match.ts`, every other line is quoted from the source record.
 */

export type PriorityLevel = "sehr-hoch" | "hoch";

export function priorityLevel(score: number): PriorityLevel {
  return score >= PRIORITY_TOP_SCORE ? "sehr-hoch" : "hoch";
}

const LEVEL_STYLE: Record<
  PriorityLevel,
  { label: string; color: string; background: string }
> = {
  "sehr-hoch": { label: "SEHR HOHE PRIORITÄT", color: "#b91c1c", background: "#fee2e2" },
  hoch: { label: "HOHE PRIORITÄT", color: "#9a3412", background: "#ffedd5" },
};

const TIME_ZONE = "Europe/Berlin";

/** How much of the description a card carries. */
const DESCRIPTION_LENGTH = 320;
/** How much of the funding-amount section a card carries. */
const AMOUNT_LENGTH = 280;
/** A deadline this short with a single date is a date, not a quoted sentence. */
const STRUCTURED_DEADLINE_LENGTH = 40;

export function formatGermanDate(date: Date): string {
  return new Intl.DateTimeFormat("de-DE", {
    timeZone: TIME_ZONE,
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
  }).format(date);
}

/** Calendar day in Berlin as a day number, so "in N Tagen" never drifts by UTC. */
function berlinDay(date: Date): number {
  const [year, month, day] = new Intl.DateTimeFormat("en-CA", {
    timeZone: TIME_ZONE,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  })
    .format(date)
    .split("-")
    .map(Number);
  return Date.UTC(year, month - 1, day) / 86_400_000;
}

function truncate(value: string, maxLength: number): string {
  const text = value.replace(/\s+/g, " ").trim();
  if (text.length <= maxLength) return text;

  const cut = text.slice(0, maxLength);
  const lastSpace = cut.lastIndexOf(" ");
  const clean = lastSpace > maxLength * 0.6 ? cut.slice(0, lastSpace) : cut;
  return `${clean.replace(/[\s,.;:–-]+$/, "")} …`;
}

/**
 * The deadline in one sentence that cannot be misread.
 *
 * A structured date (EU calls: "Einreichungsfrist: 06.10.2026") gets the days
 * left. Everything else is the source's own sentence, marked as a quote — a
 * computed date from prose would be a promise the source does not make.
 */
export function describeDeadline(deadline: string | undefined, today: Date): string {
  const text = deadline?.replace(/\s+/g, " ").trim();
  if (!text) {
    return "Keine Frist in der Quelle genannt – bitte auf der Programmseite prüfen";
  }

  const dates = Array.from(text.matchAll(/(\d{1,2})\.(\d{1,2})\.(\d{4})/g));
  if (dates.length === 1 && text.length <= STRUCTURED_DEADLINE_LENGTH) {
    const [, day, month, year] = dates[0];
    const formatted = `${day.padStart(2, "0")}.${month.padStart(2, "0")}.${year}`;
    const daysLeft =
      Date.UTC(Number(year), Number(month) - 1, Number(day)) / 86_400_000 -
      berlinDay(today);

    if (daysLeft < 0) {
      return `${formatted} – liegt in der Vergangenheit, Aktualität bitte prüfen`;
    }
    if (daysLeft === 0) return `${formatted} – endet heute`;
    if (daysLeft === 1) return `${formatted} – endet morgen`;
    return `${formatted} – noch ${daysLeft} Tage`;
  }

  return `Laut Quelle: „${truncate(text, 240)}“`;
}

function shortDescription(program: CatalogProgram): string | undefined {
  const text =
    program.summary ||
    sectionText(program, SECTION_FOR.purpose, 2000) ||
    program.description;
  return text ? truncate(text, DESCRIPTION_LENGTH) : undefined;
}

function audienceOf(program: CatalogProgram): string {
  const parts = [
    program.eligibleParties.length
      ? `Antragsberechtigt: ${program.eligibleParties.join(", ")}`
      : "",
    program.companySizes.length
      ? `Unternehmensgröße: ${program.companySizes.join(", ")}`
      : "",
    program.industries.length ? `Branchen: ${program.industries.join(", ")}` : "",
  ].filter(Boolean);

  if (parts.length > 0) return parts.join(" · ");
  return (
    sectionText(program, SECTION_FOR.audience, 240) ??
    "In der Quelle nicht strukturiert angegeben – siehe Programmseite"
  );
}

function hostOf(url: string): string {
  try {
    return new URL(url).hostname.replace(/^www\./, "");
  } catch {
    return url;
  }
}

interface Fact {
  label: string;
  value: string;
  href?: string;
}

function factsOf(change: CatalogChange, today: Date): Fact[] {
  const { program } = change;
  const link = primaryLink(change);
  const amount = sectionText(program, SECTION_FOR.amount, AMOUNT_LENGTH);
  const sourceLabel = CATALOG_SOURCE_LABELS[program.source] ?? program.source;

  return [
    { label: "Fördergeber", value: program.fundingBody ?? "Nicht angegeben" },
    { label: "Förderart", value: program.fundingTypes.join(", ") || "Nicht angegeben" },
    ...(amount ? [{ label: "Förderhöhe", value: amount }] : []),
    { label: "Zielgruppe", value: audienceOf(program) },
    { label: "Region", value: program.regions.join(", ") || "Nicht angegeben" },
    { label: "Frist", value: describeDeadline(program.deadline, today) },
    link
      ? {
          label: program.officialUrl ? "Offizieller Link" : "Link",
          value: link,
          href: link,
        }
      : { label: "Link", value: "In der Quelle kein Link angegeben" },
    program.detailUrl && program.detailUrl !== link
      ? { label: "Quelle", value: sourceLabel, href: program.detailUrl }
      : { label: "Quelle", value: sourceLabel },
    { label: "Erkannt am", value: formatGermanDate(new Date(change.detectedAt)) },
  ];
}

/** Strongest first — also when the caller already sorted, so the order is a guarantee. */
function byPriority(changes: CatalogChange[]): CatalogChange[] {
  return [...changes].sort(
    (a, b) =>
      b.topScore - a.topScore || b.detectedAt.localeCompare(a.detectedAt) || b.id - a.id
  );
}

function renderFact(fact: Fact): string {
  const value = fact.href
    ? `<a href="${escapeHtml(fact.href)}" style="color:${COLORS.link};word-break:break-all;">${escapeHtml(
        fact.label === "Quelle" ? fact.value : hostOf(fact.value)
      )}</a>`
    : escapeHtml(fact.value);

  return `<tr><td style="padding:6px 0 0 0;font-size:13px;line-height:1.45;color:${COLORS.ink};">
    <span style="color:${COLORS.faint};">${escapeHtml(fact.label)}:</span> ${value}
  </td></tr>`;
}

function renderEntry(change: CatalogChange, rank: number, today: Date): string {
  const { program } = change;
  const level = LEVEL_STYLE[priorityLevel(change.topScore)];
  const link = primaryLink(change);
  const description = shortDescription(program);

  const title = escapeHtml(program.name);
  const heading = link
    ? `<a href="${escapeHtml(link)}" style="color:${COLORS.ink};text-decoration:none;">${title}</a>`
    : title;

  const topics = change.matches
    .map(
      (match) =>
        `<span style="display:inline-block;background:#eef2ff;color:#3730a3;border-radius:10px;padding:2px 8px;margin:0 6px 4px 0;font-size:12px;">${escapeHtml(
          match.topicLabel
        )} ${match.score} %</span>`
    )
    .join("");

  const reasons = change.matches
    .slice(0, 3)
    .map(
      (match) =>
        `<li style="margin:0 0 4px 0;"><strong>${escapeHtml(match.topicLabel)}:</strong> ${escapeHtml(
          match.reasons.join(" · ")
        )}</li>`
    )
    .join("");

  const sectionLabel = (text: string) =>
    `<div style="margin-top:12px;font-size:11px;font-weight:700;letter-spacing:.05em;text-transform:uppercase;color:${COLORS.faint};">${text}</div>`;

  return `
  <tr><td style="padding:0 0 14px 0;">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:${COLORS.card};border:1px solid ${COLORS.line};border-left:4px solid ${level.color};border-radius:8px;">
      <tr><td style="padding:16px;">
        <div style="font-size:12px;line-height:1.4;">
          <span style="display:inline-block;background:${level.background};color:${level.color};font-weight:700;letter-spacing:.04em;border-radius:4px;padding:2px 8px;margin:0 6px 4px 0;">${level.label}</span>
          <span style="display:inline-block;font-weight:700;color:${COLORS.ink};margin:0 6px 4px 0;">#${rank} · Score ${change.topScore} %</span>
          <span style="display:inline-block;font-weight:700;color:#0f7b34;">NEU</span>
        </div>
        <div style="margin-top:6px;font-size:17px;font-weight:600;line-height:1.35;color:${COLORS.ink};word-wrap:break-word;">${heading}</div>
        ${description ? `<div style="margin-top:8px;font-size:14px;line-height:1.5;color:${COLORS.muted};">${escapeHtml(description)}</div>` : ""}
        ${sectionLabel("Passende mpool-Themen")}
        <div style="margin-top:4px;">${topics}</div>
        ${reasons ? `${sectionLabel("Warum passend")}<ul style="margin:4px 0 0 0;padding-left:18px;font-size:13px;line-height:1.5;color:${COLORS.muted};">${reasons}</ul>` : ""}
        <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin-top:12px;border-top:1px solid ${COLORS.line};">
          ${factsOf(change, today).map(renderFact).join("")}
        </table>
        ${
          link
            ? `<div style="margin-top:14px;"><a href="${escapeHtml(link)}" style="display:inline-block;background:${COLORS.link};color:#ffffff;padding:10px 16px;border-radius:6px;font-size:14px;font-weight:600;text-decoration:none;">Programmseite öffnen</a></div>`
            : ""
        }
      </td></tr>
    </table>
  </td></tr>`;
}

function renderTextEntry(change: CatalogChange, rank: number, today: Date): string {
  const level = LEVEL_STYLE[priorityLevel(change.topScore)];
  const description = shortDescription(change.program);

  return [
    `${rank}. [${level.label} · Score ${change.topScore} %] ${change.program.name}`,
    description ?? "",
    `mpool-Themen: ${change.matches.map((match) => `${match.topicLabel} ${match.score} %`).join(" | ")}`,
    ...change.matches
      .slice(0, 3)
      .map(
        (match) => `Warum passend (${match.topicLabel}): ${match.reasons.join(" · ")}`
      ),
    ...factsOf(change, today).map(
      (fact) =>
        `${fact.label}: ${fact.value}${fact.href && fact.href !== fact.value ? ` (${fact.href})` : ""}`
    ),
  ]
    .filter((line) => line.length > 0)
    .join("\n");
}

export interface PriorityAlertOptions {
  changes: CatalogChange[];
  /** When the delivery was created — fixed, so a retried mail is byte-identical. */
  date: Date;
  /** The score threshold in force, stated in the mail. */
  threshold: number;
  /** Candidates above the threshold that did not fit and go to the weekly digest. */
  deferred?: number;
  appUrl?: string;
  /** Banner lines above the entries — used by the preview only. */
  notes?: string[];
}

export function renderPriorityAlert({
  changes,
  date,
  threshold,
  deferred = 0,
  appUrl,
  notes = [],
}: PriorityAlertOptions): DigestContent {
  const entries = byPriority(changes);
  const count = entries.length;
  const top = entries[0]?.topScore ?? 0;
  const veryHigh = entries.filter(
    (change) => priorityLevel(change.topScore) === "sehr-hoch"
  ).length;
  const dateLabel = formatGermanDate(date);

  const programs = count === 1 ? "neues Förderprogramm" : "neue Förderprogramme";
  const subject =
    count === 0
      ? "Förderradar Prioritätsalarm: keine neuen Treffer"
      : `[Hohe Priorität] Förderradar: ${count} ${programs} für mpool – Top-Treffer ${top} %`;

  const intro =
    count === 0
      ? `Aktuell gibt es keine neuen Förderprogramme mit einem Score ab ${threshold} %.`
      : `${count} ${programs} ${count === 1 ? "passt" : "passen"} stark zu den mpool-Leistungen (Score ab ${threshold} %${veryHigh > 0 ? `, davon ${veryHigh} mit sehr hoher Priorität` : ""}). Stärkste Treffer zuerst.`;

  const deferredNote =
    deferred > 0
      ? `${deferred} weitere${deferred === 1 ? "r" : ""} neue${deferred === 1 ? "r" : ""} Treffer über dem Grenzwert ${deferred === 1 ? "hat" : "haben"} in dieser Mail keinen Platz und ${deferred === 1 ? "erscheint" : "erscheinen"} im wöchentlichen Digest.`
      : "";

  const banner = notes.length
    ? `<tr><td style="padding-bottom:14px;"><div style="background:#fef9c3;border:1px solid #fde047;border-radius:8px;padding:10px 12px;font-size:13px;line-height:1.5;color:#713f12;">${notes
        .map((note) => escapeHtml(note))
        .join("<br>")}</div></td></tr>`
    : "";

  const html = `<!doctype html>
<html lang="de">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="x-apple-disable-message-reformatting">
<title>${escapeHtml(subject)}</title>
</head>
<body style="margin:0;padding:0;background:${COLORS.page};">
<div style="display:none;max-height:0;overflow:hidden;mso-hide:all;">${escapeHtml(intro)}</div>
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:${COLORS.page};padding:20px 10px;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;">
  <tr><td align="center">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:640px;">
      <tr><td style="padding-bottom:16px;">
        <div style="font-size:12px;font-weight:700;letter-spacing:.06em;color:#b91c1c;">PRIORITÄTSALARM · ${escapeHtml(dateLabel)}</div>
        <div style="margin-top:4px;font-size:20px;font-weight:700;line-height:1.3;color:${COLORS.ink};">Neue Förderprogramme für mpool</div>
        <div style="margin-top:6px;font-size:14px;line-height:1.5;color:${COLORS.muted};">${escapeHtml(intro)}</div>
      </td></tr>
      ${banner}
      ${entries.map((change, index) => renderEntry(change, index + 1, date)).join("")}
      ${deferredNote ? `<tr><td style="padding:0 0 14px 0;font-size:13px;line-height:1.5;color:${COLORS.muted};">${escapeHtml(deferredNote)}</td></tr>` : ""}
      <tr><td style="padding-top:8px;border-top:1px solid ${COLORS.line};font-size:12px;line-height:1.6;color:${COLORS.faint};">
        ${appUrl ? `<a href="${escapeHtml(appUrl)}" style="color:${COLORS.link};">Im Förderprogramm-Finder weitersuchen</a><br>` : ""}
        Diese Mail enthält nur neu erkannte Programme. Geänderte und entfallene Programme folgen im wöchentlichen Digest.<br>
        Der Score ist die serverseitig berechnete Passgenauigkeit zu den mpool-Themen — keine Zusage über Antragsberechtigung.
        Fristen und Bedingungen bitte immer auf der offiziellen Programmseite prüfen.<br>
        ${escapeHtml(FDB_ATTRIBUTION)}
      </td></tr>
    </table>
  </td></tr>
</table>
</body>
</html>`;

  const text = [
    `Förderradar · Prioritätsalarm · ${dateLabel}`,
    ...notes,
    intro,
    ...entries.map((change, index) => renderTextEntry(change, index + 1, date)),
    deferredNote,
    appUrl ? `Weitersuchen: ${appUrl}` : "",
    "Nur neu erkannte Programme. Score = Passgenauigkeit zu den mpool-Themen, keine Zusage über Antragsberechtigung. Fristen bitte auf der offiziellen Programmseite prüfen.",
    FDB_ATTRIBUTION,
  ]
    .filter((block) => block.length > 0)
    .join("\n\n");

  return { subject, html, text };
}
